export enum Tech {
  Electron = "Electron",
  TypeScript = "TypeScript",
  MongoDB = "MongoDB",
  Express = "Express",
  React = "React",
  TanStackQuery = "TanStack Query",
  Node = "Node",
  Tailwind = "Tailwind",
  Redux = "Redux",
  Prisma = "Prisma",
  tRPC = "tRPC",
  Postgres = "Postgres",
  NextJS = "Next JS",
  ThreeJS = "Three.js",
  MUI = "MUI",
  Firebase = "Firebase",
}
